### PR TITLE
Make the parser standard compliant.

### PR DESCRIPTION
**Pull request by ralph-schleicher**
I checked the Yason parser against the test suite from JSON.org and it shows several deficencies. Therefore I added a `*parse-strict*` parameter so that the user has the choice between a relaxed (i.e. mostly backward compatible) or strict (i.e. standard compliant) JSON parser. The remaining deviations are IMHO of esthetic nature. I split the PR into several individual commits so that the changes are easier to review. Let me know what you think about it.

### CODE REVIEW

**Comment by ralph-schleicher** [comment]
Commit [820c156](https://github.com/phmarek/yason/pull/78/commits/820c1563cde0a69733ec26882b5f337bee952ceb) is a complete rewrite. The parser now passes all tests of the [JSON Parsing Test Suite](https://github.com/nst/JSONTestSuite) (with `*parse-strict*` and `*parse-duplicate-keys*` set to true). Here is the result of the "parsers are free to accept or reject content" tests:

image

Dark blue means reject, light blue means accept.

**Comment by phmarek** [comment]
Wow, that's quite a lot of stuff! I'll need some time to review all that.


But - Really? `json-checker/fail18.json` --
```json
[[[[[[[[[[[[[[[[[[[["Too deep"]]]]]]]]]]]]]]]]]]]]
```
What's wrong with that? 


```
May signal an ‘arithmetic-error’ if a JSON number can not be represented as a Lisp number.
```
With `bignum`s and `long-float`s available, I'd guess the reverse is more likely -- after all, Javascript only has 53 bits of mantissa and so can't represent all of CL's numbers with the same precision?


Re 5fc5413422d01554b740ef9f25302e92428e391b -- did you really want to include all the other parses into that branch?

**Comment by pjstirling** [comment]
JSON is usually ingested from untrusted sources, limiting the nesting is part of avoiding denial of service attacks, I assume

**Comment by ralph-schleicher** [comment]
> JSON is usually ingested from untrusted sources, limiting the nesting is part of avoiding denial of service attacks, I assume

That's correct. Deeply nested structures may eat up your stack space (with a recursive descendent parser).

**Comment by ralph-schleicher** [comment]
> With `bignum`s and `long-float`s available, I'd guess the reverse is more likely -- after all, Javascript only has 53 bits of mantissa and so can't represent all of CL's numbers with the same precision?

The problem are also DoS attacks on the parser. The number 1e100000 is too large for a `long-float` and evaluating `(* 1 (expt 10 100000))` consumes quite some CPU cycles. Simply limiting the range for the exponent does not solve the problem. If the integer part of a number has 100000 digits, you loose, too.

**Comment by ralph-schleicher** [comment]
> Re [5fc5413](https://github.com/phmarek/yason/commit/5fc5413422d01554b740ef9f25302e92428e391b) -- did you really want to include all the other parses into that branch?

No, you can omit it. I've only added it for reference.

**Comment by ralph-schleicher** [comment]
FYI, I ran a parsing benchmark on a 100 MB JSON file. Here is the result:

image

Execution times are relative to YASON upstream. **YASON strict** is the rewritten parser in strict mode. Jonathan and jsown are excluded since both ran out of memory due to the file size.

The large file is created as follows:
```
# https://github.com/boostorg/json.git
boost_json_dir = .../boost-json

large_json_SOURCES = \
$(boost_json_dir)/bench/data/apache_builds.json \
$(boost_json_dir)/bench/data/canada.json \
$(boost_json_dir)/bench/data/citm_catalog.json \
$(boost_json_dir)/bench/data/github_events.json \
$(boost_json_dir)/bench/data/gsoc-2018.json \
$(boost_json_dir)/bench/data/instruments.json \
$(boost_json_dir)/bench/data/marine_ik.json \
$(boost_json_dir)/bench/data/mesh.json \
$(boost_json_dir)/bench/data/mesh.pretty.json \
$(boost_json_dir)/bench/data/numbers.json \
$(boost_json_dir)/bench/data/random.json \
$(boost_json_dir)/bench/data/twitter.json \
$(boost_json_dir)/bench/data/twitterescaped.json \
$(boost_json_dir)/bench/data/update-center.json \
$(nil)

large.json: $(large_json_SOURCES)
	{ echo "[" ; \
	  for j in 1 2 3 4 5 6 7 ; do \
	    for f in $(large_json_SOURCES) ; do \
	      cat $$f ; echo "," ; \
	    done ; \
	  done ;  \
	  echo "null" ; \
	  echo "]" ; \
	} > $@
```

**Comment by phmarek** [comment]
Can you share the raw numbers (seconds?) as well, please? If you prefer, in a private mail?

**Comment by ralph-schleicher** [comment]
Here is the Octave script.
```
% Column labels.
lisp = {'SBCL', ...
        'CCL'};

% Row labels.
parser = {'CL-JSON', ...
          'json-streams', ...
          'shasht', ...
          'ST-JSON', ...
          'YASON', ...
          'YASON strict'};

% Table data.
time = [5.79,  nan ; ...
        8.19, 29.32; ...
        3.33, 39.63; ...
        6.95, 22.23; ...
        9.86, 58.30; ...
        5.75, 18.95];

ref = find(strcmp(parser, 'YASON'));
ratio = time ./ time(ref, :);

bar(ratio);
xticklabels(parser);
legend(lisp);
```
The large file is read from a very fast SSD, so I'm confident that I/O is not the bottleneck (the fastest reader achieves 32 MB/s).

**Comment by phmarek** [comment]
Thanks - but I meant the _performance_ _data_, ie. the runtime in seconds for each test.

**Comment by ralph-schleicher** [comment]
The `time` matrix contains the execution time for each Lisp/parser in seconds. Sorry if that wasn't clear.

**Pull request closed without merging**
