### PR TITLE
Fixed error about non applicable method of STREAM-LINE-COLUMN when *PRINT-PRETTY* is T on CCL

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Also, I've added a test ASDF system and ability to run tests like this:

    (asdf:test-syste :yason)

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
I've updated doc.xml, but wasn't able to rebuild the documentaiton. Waiting for answer in this issue: https://github.com/hanshuebner/clixdoc/issues/1

**Comment by hanshuebner** [comment]
@svetlyak40wt I believe that the clixdoc repository is not needed to create the docs from the XML file, but it has been a while since I looked at it.  Did you try to run the https://github.com/phmarek/yason/blob/master/render-doc.sh script?  What errors did you get?

**Comment by svetlyak40wt** [comment]
I've missed this script. Thank you.

OMG, I didn't touch anything XSLT related since 2008! :)))

**Comment by phmarek** [comment]
Thank you!

**Pull request merged**
