### PR TITLE
Fix alist ordering

### PR DESCRIPTION
**Pull request by samuel-jimenez**
Restore order of alist to original JSON string.

### CODE REVIEW

**Comment by samuel-jimenez** [comment]
Fix for #61.

**Comment by phmarek** [comment]
What about a `plist`?

Please add test cases so that all 3 variants are checked, with at least 2 values each.

Thanks

**Comment by samuel-jimenez** [comment]
Tests added. Hashes are unordered, so I added duplicate values into the tests.

**Comment by phmarek** [comment]
1. Please rebase your changes to the current version before sending a PR!
2. Don't override the configuration, else tests break upon a second run - always bind them locally only.
3. Merged, thanks.

**Pull request merged**
